#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

[ -f "$MBSYNCRC" ] && alias mbsync="mbsync -c $MBSYNCRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

se() {
	choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
	[ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice"
	;}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ytt="yt --skip-download --write-thumbnail" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
        ls="ls -hvN --color=auto --group-directories-first" \
	diff="diff --color=auto" \
	grep="grep --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	p="pacman" \
	up="yay -Syu" \
	ka="killall" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	b="cd .." \
	ll="ls -l" \
	la="ls -ah" \
	lla="ls -lha" \
	z="zathura" \
	nsxiv="nsxiv -b" \
	orphans="pacman -Qtdq" \
	removeorphans='pacman -Rns $(pacman -Qtdq)' \
        rcommit='curl -sL https://whatthecommit.com/index.txt'

# git
alias \
        g="git" \
        gst="git status" \
        ga="git add" \
        gc="git commit -m" \
        gp="git push" \
        gl="git pull" \
        dotfiles="git --git-dir=/home/beck/.git --work-tree=/"

# network
alias \
	publicip="curl ifconfig.me" \
	dhcp="sudo nmap --script broadcast-dhcp-discover" \
	dns="cat /etc/resolv.conf"

alias \
	lf="lfub" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport" \
	weather="curl wttr.in/tashkent" \
	temps="watch sensors" \
        t="task +OVERDUE or due:today or due:tomorrow"
