#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 120		# default 96. Set DPI. User may want to use a larger number for larger screens.
setbg &			# set the background with the `setbg` script
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

# autostart="mpd xcompmgr dunst unclutter pipewire remapd"
autostart="mpd xcompmgr dunst unclutter pipewire wireplumber pipewire-pulse remapd"

for program in $autostart; do
    pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

nextcloud --background &

# change trackpoint speed
xinput --set-prop "TPPS/2 Elan TrackPoint" "libinput Accel Profile Enabled" 1, 0
xinput --set-prop "TPPS/2 Elan TrackPoint" "libinput Accel Speed" -0.2
